### ISSUE TITLE
The React application won't build with Node v17+

### ISSUE THREAD

**Issue by durw4rd** [ttotenberg-ld/react_qr_app#5]
Seems there is an outstanding bug with Webpack and the newer versions of Node: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

It might help adding a note to the readme file to let ppl know they need to use Node versioned below v17.

**Comment by ttotenberg-ld** [comment]
Cool, thanks for the heads up! Just added a line to the readme.
